on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.2.0
            puppet: 8
            fixtures: .fixtures.yml
            allow_failure: false
    env:
      PUPPET_GEM_VERSION: "~> ${{ matrix.puppet }}.0"
    name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }} fixtures=${{ matrix.fixtures }})
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: '2.4.13'
      - name: Validate
        run: bundle exec rake check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint
      - name: Run tests
        run: bundle exec rake parallel_spec
